# Generated by Django 2.0.2 on 2018-02-07 18:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20180206_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slide',
            new_name='Presentation',
        ),
    ]
