# Generated by Django 2.0.2 on 2018-02-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_presentation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='name',
            field=models.CharField(blank=True, default='Another useless presentation', max_length=256, null=True),
        ),
    ]
