# Generated by Django 2.0.2 on 2018-02-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180207_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='presentationId',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
