# Generated by Django 2.0.2 on 2018-02-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_presentation_presentationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='pdf',
            field=models.FilePathField(blank=True, default=None, null=True),
        ),
    ]
