# Generated by Django 2.0.2 on 2018-02-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180210_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
