# Generated by Django 2.0.2 on 2018-02-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180210_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='user_files/'),
        ),
    ]
