# Generated by Django 2.0.2 on 2018-02-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180210_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='hash',
            field=models.CharField(blank=True, default='xyz', max_length=64, null=True),
        ),
    ]
