# Generated by Django 2.0.2 on 2018-02-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180210_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Another useless presentation', max_length=256, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hash', models.CharField(blank=True, default='xyz', max_length=64, null=True)),
                ('origin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Presentation')),
            ],
        ),
    ]
