# Generated by Django 2.0.2 on 2018-02-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_presentationcopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationcopy',
            name='last_view',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
